//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInvoice
    {
        public int CustomerInvoiceID { get; set; }
        public string CustomerInvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerPhoneNo { get; set; }
        public string CustomerEmailID { get; set; }
        public int InvoiceType { get; set; }
        public Nullable<int> SalesPersonID { get; set; }
        public int CurrencyID { get; set; }
        public Nullable<decimal> ExRate { get; set; }
        public string ReferenceNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> SGSTAmount { get; set; }
        public Nullable<decimal> CGSTAmount { get; set; }
        public Nullable<decimal> IGSTAmount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<int> AcJournalID { get; set; }
        public bool StatusClose { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
        public decimal InvoiceTotal { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> AcFinancialYearID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public int PaymentModeId { get; set; }
        public int AcHeadId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> InvoiceTotalFC { get; set; }
        public Nullable<decimal> DiscountAmountFC { get; set; }
    }
}
