//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int ID { get; set; }
        public int EnquiryID { get; set; }
        public int ProductFamilyID { get; set; }
        public int EquipmentTypeID { get; set; }
        public string EquipmentName { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int Quantity { get; set; }
        public decimal UnitRate { get; set; }
        public decimal Amount { get; set; }
        public int EquipmentStatusID { get; set; }
        public int PurchaseOrderID { get; set; }
        public Nullable<int> QuotationId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string NominalCapacity { get; set; }
        public bool Refrigerant { get; set; }
        public string EfficientType { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
    }
}
