//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimationMaster
    {
        public int ID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Remarks { get; set; }
    }
}
