//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRN
    {
        public int GRNID { get; set; }
        public string GRNNO { get; set; }
        public Nullable<System.DateTime> GRNDATE { get; set; }
        public Nullable<int> SUPPLIERID { get; set; }
        public Nullable<int> PURCHASEORDERID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> FYearID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
