//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRNDetail
    {
        public int GRNDetailID { get; set; }
        public Nullable<int> GRNID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public int EquipmentTypeID { get; set; }
        public string Description { get; set; }
        public string Model { get; set; }
        public Nullable<int> ItemUnitID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> JobHandOverID { get; set; }
        public string ProjectNo { get; set; }
    }
}
