//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPurchaseOrderDetail
    {
        public int ID { get; set; }
        public int JobHandOverID { get; set; }
        public string PONumber { get; set; }
        public System.DateTime PODate { get; set; }
        public decimal OrderValue { get; set; }
        public Nullable<decimal> VatPercent { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public decimal TotalValue { get; set; }
        public int VarNo { get; set; }
        public Nullable<int> QuotationId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<int> MRequestID { get; set; }
    }
}
