//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPaymentTerm
    {
        public int ID { get; set; }
        public Nullable<int> JobHandOverID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public Nullable<int> DueDays { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Terms { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
