//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialIssue
    {
        public int MIssueID { get; set; }
        public string IssueNo { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<int> IssuedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string Remarks { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int JobHandOverID { get; set; }
        public int RequestedBy { get; set; }
    }
}
