//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HVACEntities : DbContext
    {
        public HVACEntities()
            : base("name=HVACEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcCompany> AcCompanies { get; set; }
        public virtual DbSet<AcFinancialYear> AcFinancialYears { get; set; }
        public virtual DbSet<BondType> BondTypes { get; set; }
        public virtual DbSet<BranchMaster> BranchMasters { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<BuildingType> BuildingTypes { get; set; }
        public virtual DbSet<BusinessType> BusinessTypes { get; set; }
        public virtual DbSet<CityMaster> CityMasters { get; set; }
        public virtual DbSet<ClientMaster> ClientMasters { get; set; }
        public virtual DbSet<CountryMaster> CountryMasters { get; set; }
        public virtual DbSet<CurrencyMaster> CurrencyMasters { get; set; }
        public virtual DbSet<CustomerMaster> CustomerMasters { get; set; }
        public virtual DbSet<DashBoardInfo> DashBoardInfoes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<DocumentMaster> DocumentMasters { get; set; }
        public virtual DbSet<DocumentNoSetup> DocumentNoSetups { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<EnquirySource> EnquirySources { get; set; }
        public virtual DbSet<EnquiryStage> EnquiryStages { get; set; }
        public virtual DbSet<EnquiryStatu> EnquiryStatus { get; set; }
        public virtual DbSet<EntityType> EntityTypes { get; set; }
        public virtual DbSet<EquipmentStatu> EquipmentStatus { get; set; }
        public virtual DbSet<LocationMaster> LocationMasters { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<MenuAccessLevel> MenuAccessLevels { get; set; }
        public virtual DbSet<Priority> Priorities { get; set; }
        public virtual DbSet<ProductFamily> ProductFamilies { get; set; }
        public virtual DbSet<QuotationStatu> QuotationStatus { get; set; }
        public virtual DbSet<QuotationTemplate> QuotationTemplates { get; set; }
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<UserInBranch> UserInBranches { get; set; }
        public virtual DbSet<UserRegistration> UserRegistrations { get; set; }
        public virtual DbSet<Vertical> Verticals { get; set; }
        public virtual DbSet<Warranty> Warranties { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<BriefScope> BriefScopes { get; set; }
        public virtual DbSet<PeriodLock> PeriodLocks { get; set; }
        public virtual DbSet<GeneralSetup> GeneralSetups { get; set; }
        public virtual DbSet<GeneralSetupType> GeneralSetupTypes { get; set; }
        public virtual DbSet<CurrencyRate> CurrencyRates { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<AcHead> AcHeads { get; set; }
        public virtual DbSet<AssignedStatu> AssignedStatus { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<SupplierMaster> SupplierMasters { get; set; }
        public virtual DbSet<CustomerInvoice> CustomerInvoices { get; set; }
        public virtual DbSet<CustomerInvoiceDetail> CustomerInvoiceDetails { get; set; }
        public virtual DbSet<SupplierType> SupplierTypes { get; set; }
        public virtual DbSet<JobWarranty> JobWarranties { get; set; }
        public virtual DbSet<PaymentInstrument> PaymentInstruments { get; set; }
        public virtual DbSet<JobPaymentTerm> JobPaymentTerms { get; set; }
        public virtual DbSet<ProjectPrefix> ProjectPrefixes { get; set; }
        public virtual DbSet<JobHandover> JobHandovers { get; set; }
        public virtual DbSet<SupplierInvoice> SupplierInvoices { get; set; }
        public virtual DbSet<EquipmentType> EquipmentTypes { get; set; }
        public virtual DbSet<EstimationCategory> EstimationCategories { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<SupplierInvoiceDetail> SupplierInvoiceDetails { get; set; }
        public virtual DbSet<ItemUnit> ItemUnits { get; set; }
        public virtual DbSet<EstimationMaster> EstimationMasters { get; set; }
        public virtual DbSet<Port> Ports { get; set; }
        public virtual DbSet<EstimationDetail> EstimationDetails { get; set; }
        public virtual DbSet<EquipmentExclusion> EquipmentExclusions { get; set; }
        public virtual DbSet<EquipmentScopeofwork> EquipmentScopeofworks { get; set; }
        public virtual DbSet<EquipmentWarranty> EquipmentWarranties { get; set; }
        public virtual DbSet<QuotationExclusion> QuotationExclusions { get; set; }
        public virtual DbSet<QuotationScopeofwork> QuotationScopeofworks { get; set; }
        public virtual DbSet<TermsCondition> TermsConditions { get; set; }
        public virtual DbSet<PaymentTerm> PaymentTerms { get; set; }
        public virtual DbSet<QuotationWarranty> QuotationWarranties { get; set; }
        public virtual DbSet<JobBondDetail> JobBondDetails { get; set; }
        public virtual DbSet<JobPurchaseOrderDetail> JobPurchaseOrderDetails { get; set; }
        public virtual DbSet<PurchaseOrderOtherDetail> PurchaseOrderOtherDetails { get; set; }
        public virtual DbSet<PurchaseOrderUserComment> PurchaseOrderUserComments { get; set; }
        public virtual DbSet<POBank> POBanks { get; set; }
        public virtual DbSet<POCompressorWarranty> POCompressorWarranties { get; set; }
        public virtual DbSet<PODeliveryTerm> PODeliveryTerms { get; set; }
        public virtual DbSet<POINCOTerm> POINCOTerms { get; set; }
        public virtual DbSet<POPaymentTerm> POPaymentTerms { get; set; }
        public virtual DbSet<PORegrigerant> PORegrigerants { get; set; }
        public virtual DbSet<GRN> GRNs { get; set; }
        public virtual DbSet<QuotationContact> QuotationContacts { get; set; }
        public virtual DbSet<EnquiryClient> EnquiryClients { get; set; }
        public virtual DbSet<StockOpening> StockOpenings { get; set; }
        public virtual DbSet<GRNDetail> GRNDetails { get; set; }
        public virtual DbSet<MaterialIssue> MaterialIssues { get; set; }
        public virtual DbSet<MaterialIssueDetail> MaterialIssueDetails { get; set; }
        public virtual DbSet<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual DbSet<MaterialRequest> MaterialRequests { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<EmployeeMaster> EmployeeMasters { get; set; }
        public virtual DbSet<MaterialRequestDetail> MaterialRequestDetails { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<PurchaseOrderNote> PurchaseOrderNotes { get; set; }
        public virtual DbSet<MaterialApproval> MaterialApprovals { get; set; }
        public virtual DbSet<MaterialApprovalDetail> MaterialApprovalDetails { get; set; }
        public virtual DbSet<PurchaseOrderApproval> PurchaseOrderApprovals { get; set; }
        public virtual DbSet<EnquiryType> EnquiryTypes { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<EnquiryEmployee> EnquiryEmployees { get; set; }
        public virtual DbSet<Enquiry> Enquiries { get; set; }
        public virtual DbSet<Quotation> Quotations { get; set; }
        public virtual DbSet<QuotationDetail> QuotationDetails { get; set; }
        public virtual DbSet<Estimation> Estimations { get; set; }
    }
}
