//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderOtherDetail
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> PurchaseOrderID { get; set; }
        public Nullable<System.DateTime> DrawingApprovalDate { get; set; }
        public Nullable<System.DateTime> ExFactoryDate { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public string Remarks { get; set; }
    }
}
