//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation
    {
        public int QuotationID { get; set; }
        public int EnquiryID { get; set; }
        public string QuotationNo { get; set; }
        public Nullable<System.DateTime> QuotationDate { get; set; }
        public int Version { get; set; }
        public string ContactPerson { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string PaymentTerms { get; set; }
        public string TermsandConditions { get; set; }
        public string Salutation { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> QuotationValue { get; set; }
        public string SubjectText { get; set; }
        public string Warranty { get; set; }
        public string ScopeofWork { get; set; }
        public Nullable<int> QuotationStatusID { get; set; }
        public Nullable<int> EngineerID { get; set; }
        public string ClientDetail { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string Exclusions { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string QuotationTo { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> VATPercent { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public string Validity { get; set; }
        public string DeliveryTerms { get; set; }
        public string ProjectRef { get; set; }
        public bool ApplyMargin { get; set; }
        public Nullable<decimal> MarginPercent { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> SellingValue { get; set; }
        public bool DirectQuotation { get; set; }
        public int ClientPOID { get; set; }
    }
}
