//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceStatus
    {
        public int ServiceStatusID { get; set; }
        public string ServiceStatusName { get; set; }
        public string ServiceStatusDescription { get; set; }
        public int StatusOrder { get; set; } // For workflow ordering
        public string StatusColor { get; set; } // For UI display
        public bool IsActive { get; set; }
        public bool IsClosed { get; set; } // Indicates if this is a final status
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        
        // Navigation properties
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
    }
}
