//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ServiceRequestVM
    {
        public int ServiceRequestID { get; set; }
        
        [Required(ErrorMessage = "Customer is required")]
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        
        [Required(ErrorMessage = "Equipment is required")]
        public int EquipmentID { get; set; }
        public string EquipmentName { get; set; }
        
        [Required(ErrorMessage = "Priority is required")]
        public int PriorityID { get; set; }
        public string PriorityName { get; set; }
        
        [Required(ErrorMessage = "Status is required")]
        public int ServiceStatusID { get; set; }
        public string StatusName { get; set; }
        
        [Required(ErrorMessage = "Creation Date is required")]
        public System.DateTime CreationDate { get; set; }
        
        [Required(ErrorMessage = "Created By is required")]
        public int CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        
        [Required(ErrorMessage = "Service Description is required")]
        [StringLength(1000, ErrorMessage = "Service Description cannot exceed 1000 characters")]
        public string ServiceDescription { get; set; }
        
        [Required(ErrorMessage = "Service Type is required")]
        public int ServiceTypeID { get; set; }
        public string ServiceTypeName { get; set; }
        
        // Additional fields
        public string ServiceRequestNo { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string AssignedTo { get; set; }
        public string ResolutionNotes { get; set; }
        public Nullable<decimal> EstimatedCost { get; set; }
        public Nullable<decimal> ActualCost { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string Location { get; set; }
        public string Remarks { get; set; }
        
        // Audit fields
        public Nullable<int> UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> AcFinancialYearID { get; set; }
        public string FinancialYearName { get; set; }
    }
}
