//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequest
    {
        public int ServiceRequestID { get; set; }
        public int CustomerID { get; set; }
        public int EquipmentID { get; set; }
        public int PriorityID { get; set; }
        public int ServiceStatusID { get; set; } // Changed from StatusID
        public System.DateTime CreationDate { get; set; }
        public int CreatedBy { get; set; }
        public string ServiceDescription { get; set; }
        public int ServiceTypeID { get; set; }
        
        // Additional service-specific fields
        public string ServiceRequestNo { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string AssignedTo { get; set; }
        public string ResolutionNotes { get; set; }
        public Nullable<decimal> EstimatedCost { get; set; }
        public Nullable<decimal> ActualCost { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string Location { get; set; }
        public string Remarks { get; set; }
        
        // Audit fields
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> AcFinancialYearID { get; set; }
        
        // Navigation properties
        public virtual CustomerMaster CustomerMaster { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual ServiceStatus ServiceStatus { get; set; } // Updated navigation
        public virtual ServiceType ServiceType { get; set; }
        public virtual UserRegistration CreatedByUser { get; set; }
        public virtual UserRegistration UpdatedByUser { get; set; }
        public virtual BranchMaster BranchMaster { get; set; }
        public virtual AcFinancialYear AcFinancialYear { get; set; }
    }
}
