//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierInvoice
    {
        public int SupplierInvoiceID { get; set; }
        public int SupplierID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> AccompanyID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> AcJOurnalID { get; set; }
        public Nullable<int> AcDiscJournalID { get; set; }
        public Nullable<int> AcHeadID { get; set; }
        public Nullable<int> FyearID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<bool> StatusClose { get; set; }
        public Nullable<decimal> InvoiceTotal { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<int> SupplierTypeId { get; set; }
        public Nullable<int> CurrencyID { get; set; }
    
        public virtual SupplierMaster SupplierMaster { get; set; }
    }
}
