//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityMaster
    {
        public int CityID { get; set; }
        public string City { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string CityCode { get; set; }
        public Nullable<bool> IsHub { get; set; }
        public string CountryCode { get; set; }
    }
}
