//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMaster
    {
        public int EmployeeID { get; set; }
        public string EmployeeCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<bool> StatusActive { get; set; }
        public int CountryID { get; set; }
        public int CityID { get; set; }
        public string Location { get; set; }
        public string PinCode { get; set; }
        public System.DateTime JoinDate { get; set; }
        public int DesignationID { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string employeeprefix { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public bool Approver { get; set; }
    }
}
