//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enquiry
    {
        public int EnquiryID { get; set; }
        public System.DateTime EnquiryDate { get; set; }
        public string EnquiryNo { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<int> DueDays { get; set; }
        public int EnquiryStageID { get; set; }
        public string EntityTypeIDs { get; set; }
        public string AssignedEmployees { get; set; }
        public int PriorityID { get; set; }
        public int VerticalsID { get; set; }
        public int EnquiryStatusID { get; set; }
        public int BuildingTypeID { get; set; }
        public int EnquirySourceID { get; set; }
        public int CityID { get; set; }
        public int CountryID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> AcFinancialYearID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> JobHandOverID { get; set; }
        public string ProjectPrefix { get; set; }
        public int EnquiryTypeID { get; set; }
        public int ClientID { get; set; }
    }
}
