//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estimation
    {
        public int EstimationID { get; set; }
        public string EstimationNo { get; set; }
        public System.DateTime EstimationDate { get; set; }
        public int VarNo { get; set; }
        public int EnquiryID { get; set; }
        public int EmployeeID { get; set; }
        public string Notes { get; set; }
        public int CurrencyID { get; set; }
        public decimal ExchangeRate { get; set; }
        public Nullable<decimal> TotalFCValue { get; set; }
        public Nullable<decimal> TotalLCValue { get; set; }
        public Nullable<int> JobHandOverID { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> FYearID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> PaymentDays { get; set; }
        public Nullable<int> FreeServiceDays { get; set; }
        public Nullable<int> ChargeableMonth { get; set; }
        public Nullable<decimal> FinChargePercent { get; set; }
        public Nullable<decimal> FinCharge { get; set; }
        public Nullable<decimal> FinPerMonthPercent { get; set; }
        public Nullable<decimal> FinPerMonth { get; set; }
        public Nullable<decimal> EquipmentsTotal { get; set; }
        public Nullable<decimal> AccessoriesTotal { get; set; }
        public Nullable<decimal> FreightTotal { get; set; }
        public Nullable<decimal> FinanceChargesTotal { get; set; }
        public Nullable<decimal> LocalChargesTotal { get; set; }
        public Nullable<decimal> OtherChargesTotal { get; set; }
        public Nullable<decimal> MarginPercent { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<decimal> SellingValue { get; set; }
        public Nullable<decimal> LandingCost { get; set; }
        public Nullable<decimal> SoharValue { get; set; }
        public Nullable<decimal> SoharValueOMR { get; set; }
        public Nullable<decimal> TotalLandingCostOMR { get; set; }
        public Nullable<decimal> LandingCostOMR { get; set; }
    }
}
