//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimationDetail
    {
        public int EstimationDetailID { get; set; }
        public Nullable<int> EstimationID { get; set; }
        public Nullable<int> EstimationCategoryID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public string Description { get; set; }
        public string Model { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> FValue { get; set; }
        public Nullable<decimal> LValue { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> EstimationMasterID { get; set; }
        public decimal ExchangeRate { get; set; }
        public Nullable<decimal> SellingUnitRate { get; set; }
        public Nullable<decimal> AppliedFactor { get; set; }
    }
}
