//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobBondDetail
    {
        public int ID { get; set; }
        public int JobHandOverID { get; set; }
        public int BondTypeID { get; set; }
        public bool BondTypeAdded { get; set; }
        public decimal BondValue { get; set; }
        public int BondValidity { get; set; }
        public System.DateTime BondIssueDate { get; set; }
        public System.DateTime BondExpiryDate { get; set; }
        public Nullable<int> JobPurchaseOrderDetailID { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<decimal> SalesValue { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
