//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobHandover
    {
        public int JobHandOverID { get; set; }
        public System.DateTime JobDate { get; set; }
        public string ProjectPrefix { get; set; }
        public string ProjectNumber { get; set; }
        public Nullable<int> MaxVarNo { get; set; }
        public int EnquiryID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ProjectTitle { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string Site { get; set; }
        public string DeliveryLocation { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> JobValue { get; set; }
        public Nullable<decimal> JobCost { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<decimal> MarginPercent { get; set; }
        public Nullable<decimal> VatPercentage { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public bool IsDeleted { get; set; }
        public bool Completed { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
