//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobValue
    {
        public int JobValueID { get; set; }
        public Nullable<int> JobHandoverID { get; set; }
        public string JobValue1 { get; set; }
        public Nullable<int> TotalCost { get; set; }
        public Nullable<int> Margin { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<int> Vat { get; set; }
    }
}
