//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialRequest
    {
        public int MRequestID { get; set; }
        public string MRNo { get; set; }
        public System.DateTime MRDate { get; set; }
        public int RequestedBy { get; set; }
        public Nullable<int> StoreKeeperID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> JobHandOverID { get; set; }
        public Nullable<int> JobPurchaseOrderDetailID { get; set; }
    }
}
