//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialRequestDetail
    {
        public int MRequestDetailID { get; set; }
        public Nullable<int> MRequestID { get; set; }
        public Nullable<int> JobHandOverID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public Nullable<int> EquipmentTypeID { get; set; }
        public string Description { get; set; }
        public string Model { get; set; }
        public Nullable<int> ItemUnitID { get; set; }
        public string StockStatus { get; set; }
        public Nullable<int> EstimationID { get; set; }
        public Nullable<int> QuotationID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> PurchaseOrderID { get; set; }
        public Nullable<int> MaterialIssueID { get; set; }
        public bool ReadytoIssue { get; set; }
        public bool ReadytoPO { get; set; }
        public Nullable<int> POApprovalLogID { get; set; }
        public Nullable<int> IssueApprovalLogID { get; set; }
    }
}
