//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialIssueDetail
    {
        public int IssueDetailID { get; set; }
        public Nullable<int> MIssueID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<int> EquipmentTypeID { get; set; }
        public Nullable<int> ItemUnitID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
    }
}
