//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int PurchaseOrderID { get; set; }
        public string PurchaseOrderNo { get; set; }
        public System.DateTime PurchaseOrderDate { get; set; }
        public int SupplierID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> FYearID { get; set; }
        public Nullable<int> PortID { get; set; }
        public Nullable<int> Revision { get; set; }
        public string PaymentTerms { get; set; }
        public Nullable<int> OriginCountryID { get; set; }
        public string INCOTerms { get; set; }
        public string DeliveryEx { get; set; }
        public int CurrencyID { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string SONoRef { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string DeliveryTerms { get; set; }
        public Nullable<int> Bank { get; set; }
        public Nullable<decimal> POValue { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public Nullable<decimal> VATPercent { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CompressorWarranty { get; set; }
        public string Refrigerant { get; set; }
        public Nullable<decimal> FreightCharges { get; set; }
        public Nullable<decimal> OriginCharges { get; set; }
        public Nullable<decimal> FinanceCharges { get; set; }
        public Nullable<decimal> FinancePercent { get; set; }
        public Nullable<int> UnitWarrantyID { get; set; }
        public string RevisionRemarks { get; set; }
        public Nullable<decimal> PreviousValue { get; set; }
        public string ReviewedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> AuthorizedBy { get; set; }
    }
}
