//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail
    {
        public int PurchaseOrderDetailID { get; set; }
        public int PurchaseOrderID { get; set; }
        public int EquipmentTypeID { get; set; }
        public int EquipmentID { get; set; }
        public string Description { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public int ItemUnitID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ProjectNo { get; set; }
        public Nullable<int> JobHandOverID { get; set; }
        public Nullable<int> EstimationID { get; set; }
        public Nullable<int> QuotationID { get; set; }
        public Nullable<int> MRequestID { get; set; }
    }
}
