//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationContact
    {
        public int ID { get; set; }
        public Nullable<int> QuotationID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ContactName { get; set; }
        public string EmailID { get; set; }
        public string PhoneNo { get; set; }
    }
}
