//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationDetail
    {
        public int QuotationDetailID { get; set; }
        public int QuotationID { get; set; }
        public int EstimationCategoryID { get; set; }
        public int EquipmentID { get; set; }
        public string Description { get; set; }
        public string Model { get; set; }
        public int UnitID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitRate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> EquipmentStatusID { get; set; }
        public Nullable<int> PurchaseOrderID { get; set; }
        public Nullable<int> EstimationMasterID { get; set; }
        public Nullable<int> EstimationDetailID { get; set; }
        public Nullable<int> EstimationID { get; set; }
        public Nullable<decimal> SellingUnitRate { get; set; }
        public Nullable<decimal> AppliedFactor { get; set; }
    }
}
