//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationScopeofwork
    {
        public int ID { get; set; }
        public Nullable<int> QuotationID { get; set; }
        public string Description { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public string Model { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public bool Airmech { get; set; }
        public bool client { get; set; }
    }
}
